"""
Ham radio canned data structures used for various fields and lookups
"""

adif_enums = {
    'mode': ['AM',
             'ARDOP',
             'ATV',
             'CHIP',
             'CLO',
             'CONTESTI',
             'CW',
             'DIGITALVOICE',
             'DOMINO',
             'DYNAMIC',
             'FAX',
             'FM',
             'FSK441',
             'FT8',
             'HELL',
             'ISCAT',
             'JT4',
             'JT6M',
             'JT9',
             'JT44',
             'JT65',
             'MFSK',
             'MSK144',
             'MT63',
             'OLIVIA',
             'OPERA',
             'PAC',
             'PAX',
             'PKT',
             'PSK',
             'PSK2K',
             'Q15',
             'QRA64',
             'ROS',
             'RTTY',
             'RTTYM',
             'SSB',
             'SSTV',
             'T10',
             'THOR',
             'THRB',
             'TOR',
             'V4',
             'VOI',
             'WINMOR',
             'WSPR', ],
    'mode_deprecated': ['AMTORFEC',
                        'ASCI',
                        'C4FM',
                        'CHIP64',
                        'CHIP128',
                        'DOMINOF',
                        'DSTAR',
                        'FMHELL',
                        'FSK31',
                        'GTOR',
                        'HELL80',
                        'HFSK',
                        'JT4A',
                        'JT4B',
                        'JT4C',
                        'JT4D',
                        'JT4E',
                        'JT4F',
                        'JT4G',
                        'JT65A',
                        'JT65B',
                        'JT65C',
                        'MFSK8',
                        'MFSK16',
                        'PAC2',
                        'PAC3',
                        'PAX2',
                        'PCW',
                        'PSK10',
                        'PSK31',
                        'PSK63',
                        'PSK63F',
                        'PSK125',
                        'PSKAM10',
                        'PSKAM31',
                        'PSKAM50',
                        'PSKFEC31',
                        'PSKHELL',
                        'QPSK31',
                        'QPSK63',
                        'QPSK125',
                        'THRBX', ],
    # submode with required main mode
    'sub_mode_with_parent_mode': [('8PSK125', 'PSK'),
                                  ('8PSK125F', 'PSK'),
                                  ('8PSK125FL', 'PSK'),
                                  ('8PSK250', 'PSK'),
                                  ('8PSK250F', 'PSK'),
                                  ('8PSK250FL', 'PSK'),
                                  ('8PSK500', 'PSK'),
                                  ('8PSK500F', 'PSK'),
                                  ('8PSK1000', 'PSK'),
                                  ('8PSK1000F', 'PSK'),
                                  ('8PSK1200F', 'PSK'),
                                  ('AMTORFEC', 'TOR'),
                                  ('ASCI', 'RTTY'),
                                  ('C4FM', 'DIGITALVOICE'),
                                  ('CHIP64', 'CHIP'),
                                  ('CHIP128', 'CHIP'),
                                  ('DMR', 'DIGITALVOICE'),
                                  ('DOM-M', 'DOMINO'),
                                  ('DOM4', 'DOMINO'),
                                  ('DOM5', 'DOMINO'),
                                  ('DOM8', 'DOMINO'),
                                  ('DOM11', 'DOMINO'),
                                  ('DOM16', 'DOMINO'),
                                  ('DOM22', 'DOMINO'),
                                  ('DOM44', 'DOMINO'),
                                  ('DOM88', 'DOMINO'),
                                  ('DOMINOEX', 'DOMINO'),
                                  ('DOMINOF', 'DOMINO'),
                                  ('DSTAR', 'DIGITALVOICE'),
                                  ('FMHELL', 'HELL'),
                                  ('FREEDV', 'DIGITALVOICE'),
                                  ('FSK31', 'PSK'),
                                  ('FSKHELL', 'HELL'),
                                  ('FSQCALL', 'MFSK'),
                                  ('FST4', 'MFSK'),
                                  ('FST4W', 'MFSK'),
                                  ('FT4', 'MFSK'),
                                  ('GTOR', 'TOR'),
                                  ('HELL80', 'HELL'),
                                  ('HELLX5', 'HELL'),
                                  ('HELLX9', 'HELL'),
                                  ('HFSK', 'HELL'),
                                  ('ISCAT-A', 'ISCAT'),
                                  ('ISCAT-B', 'ISCAT'),
                                  ('JS8', 'MFSK'),
                                  ('JT4A', 'JT4'),
                                  ('JT4B', 'JT4'),
                                  ('JT4C', 'JT4'),
                                  ('JT4D', 'JT4'),
                                  ('JT4E', 'JT4'),
                                  ('JT4F', 'JT4'),
                                  ('JT4G', 'JT4'),
                                  ('JT9-1', 'JT9'),
                                  ('JT9-2', 'JT9'),
                                  ('JT9-5', 'JT9'),
                                  ('JT9-10', 'JT9'),
                                  ('JT9-30', 'JT9'),
                                  ('JT9A', 'JT9'),
                                  ('JT9B', 'JT9'),
                                  ('JT9C', 'JT9'),
                                  ('JT9D', 'JT9'),
                                  ('JT9E', 'JT9'),
                                  ('JT9E FAST', 'JT9'),
                                  ('JT9F', 'JT9'),
                                  ('JT9F FAST', 'JT9'),
                                  ('JT9G', 'JT9'),
                                  ('JT9G FAST', 'JT9'),
                                  ('JT9H', 'JT9'),
                                  ('JT9H FAST', 'JT9'),
                                  ('JT65A', 'JT65'),
                                  ('JT65B', 'JT65'),
                                  ('JT65B2', 'JT65'),
                                  ('JT65C', 'JT65'),
                                  ('JT65C2', 'JT65'),
                                  ('JTMS', 'MFSK'),
                                  ('LSB', 'SSB'),
                                  ('M17', 'DIGITALVOICE'),
                                  ('MFSK4', 'MFSK'),
                                  ('MFSK8', 'MFSK'),
                                  ('MFSK11', 'MFSK'),
                                  ('MFSK16', 'MFSK'),
                                  ('MFSK22', 'MFSK'),
                                  ('MFSK31', 'MFSK'),
                                  ('MFSK32', 'MFSK'),
                                  ('MFSK64', 'MFSK'),
                                  ('MFSK64L', 'MFSK'),
                                  ('MFSK128', 'MFSK'),
                                  ('MFSK128L', 'MFSK'),
                                  ('NAVTEX', 'TOR'),
                                  ('OLIVIA 4/125', 'OLIVIA'),
                                  ('OLIVIA 4/250', 'OLIVIA'),
                                  ('OLIVIA 8/250', 'OLIVIA'),
                                  ('OLIVIA 8/500', 'OLIVIA'),
                                  ('OLIVIA 16/500', 'OLIVIA'),
                                  ('OLIVIA 16/1000', 'OLIVIA'),
                                  ('OLIVIA 32/1000', 'OLIVIA'),
                                  ('OPERA-BEACON', 'OPERA'),
                                  ('OPERA-QSO', 'OPERA'),
                                  ('PAC2', 'PAC'),
                                  ('PAC3', 'PAC'),
                                  ('PAC4', 'PAC'),
                                  ('PAX2', 'PAX'),
                                  ('PCW', 'CW'),
                                  ('PSK10', 'PSK'),
                                  ('PSK31', 'PSK'),
                                  ('PSK63', 'PSK'),
                                  ('PSK63F', 'PSK'),
                                  ('PSK63RC10', 'PSK'),
                                  ('PSK63RC20', 'PSK'),
                                  ('PSK63RC32', 'PSK'),
                                  ('PSK63RC4', 'PSK'),
                                  ('PSK63RC5', 'PSK'),
                                  ('PSK125', 'PSK'),
                                  ('PSK125RC10', 'PSK'),
                                  ('PSK125RC12', 'PSK'),
                                  ('PSK125RC16', 'PSK'),
                                  ('PSK125RC4', 'PSK'),
                                  ('PSK125RC5', 'PSK'),
                                  ('PSK250', 'PSK'),
                                  ('PSK250RC2', 'PSK'),
                                  ('PSK250RC3', 'PSK'),
                                  ('PSK250RC5', 'PSK'),
                                  ('PSK250RC6', 'PSK'),
                                  ('PSK250RC7', 'PSK'),
                                  ('PSK500', 'PSK'),
                                  ('PSK500RC2', 'PSK'),
                                  ('PSK500RC3', 'PSK'),
                                  ('PSK500RC4', 'PSK'),
                                  ('PSK800RC2', 'PSK'),
                                  ('PSK1000', 'PSK'),
                                  ('PSK1000RC2', 'PSK'),
                                  ('PSKAM10', 'PSK'),
                                  ('PSKAM31', 'PSK'),
                                  ('PSKAM50', 'PSK'),
                                  ('PSKFEC31', 'PSK'),
                                  ('PSKHELL', 'HELL'),
                                  ('QPSK31', 'PSK'),
                                  ('Q65', 'MFSK'),
                                  ('QPSK63', 'PSK'),
                                  ('QPSK125', 'PSK'),
                                  ('QPSK250', 'PSK'),
                                  ('QPSK500', 'PSK'),
                                  ('QRA64A', 'QRA64'),
                                  ('QRA64B', 'QRA64'),
                                  ('QRA64C', 'QRA64'),
                                  ('QRA64D', 'QRA64'),
                                  ('QRA64E', 'QRA64'),
                                  ('ROS-EME', 'ROS'),
                                  ('ROS-HF', 'ROS'),
                                  ('ROS-MF', 'ROS'),
                                  ('SIM31', 'PSK'),
                                  ('SITORB', 'TOR'),
                                  ('SLOWHELL', 'HELL'),
                                  ('THOR-M', 'THOR'),
                                  ('THOR4', 'THOR'),
                                  ('THOR5', 'THOR'),
                                  ('THOR8', 'THOR'),
                                  ('THOR11', 'THOR'),
                                  ('THOR16', 'THOR'),
                                  ('THOR22', 'THOR'),
                                  ('THOR25X4', 'THOR'),
                                  ('THOR50X1', 'THOR'),
                                  ('THOR50X2', 'THOR'),
                                  ('THOR100', 'THOR'),
                                  ('THRBX', 'THRB'),
                                  ('THRBX1', 'THRB'),
                                  ('THRBX2', 'THRB'),
                                  ('THRBX4', 'THRB'),
                                  ('THROB1', 'THRB'),
                                  ('THROB2', 'THRB'),
                                  ('THROB4', 'THRB'),
                                  ('USB', 'SSB'),
                                  ('VARA HF', 'DYNAMIC'),
                                  ('VARA SATELLITE', 'DYNAMIC'),
                                  ('VARA FM 1200', 'DYNAMIC'),
                                  ('VARA FM 9600', 'DYNAMIC'), ],
    'prop_mode': [('AS', 'Aircraft Scatter'),
                  ('AUE', 'Aurora-E'),
                  ('AUR', 'Aurora'),
                  ('BS', 'Back scatter'),
                  ('ECH', 'EchoLink'),
                  ('EME', 'Earth-Moon-Earth'),
                  ('ES', 'Sporadic E'),
                  ('F2', 'F2 Reflection'),
                  ('FAI', 'Field Aligned Irregularities'),
                  ('GWAVE', 'Ground Wave'),
                  ('INTERNET', 'Internet-assisted'),
                  ('ION', 'Ionoscatter'),
                  ('IRL', 'IRLP'),
                  ('LOS', 'Line of Sight (includes transmission through obstacles such as walls)'),
                  ('MS', 'Meteor scatter'),
                  ('RPT', 'Terrestrial or atmospheric repeater or transponder'),
                  ('RS', 'Rain scatter'),
                  ('SAT', 'Satellite'),
                  ('TEP', 'Trans-equatorial'),
                  ('TR', 'Tropospheric ducting'),
                  ],
    'arrl_sect': [('AL', 'Alabama'),
                  ('AK', 'Alaska'),
                  ('AB', 'Alberta'),
                  ('AR', 'Arkansas'),
                  ('AZ', 'Arizona'),
                  ('BC', 'British Columbia'),
                  ('CO', 'Colorado'),
                  ('CT', 'Connecticut'),
                  ('DE', 'Delaware'),
                  ('EB', 'East Bay'),
                  ('EMA', 'Eastern Massachusetts'),
                  ('ENY', 'Eastern New York'),
                  ('EPA', 'Eastern Pennsylvania'),
                  ('EWA', 'Eastern Washington'),
                  ('GA', 'Georgia'),
                  ('GTA', 'Greater Toronto Area'),
                  ('ID', 'Idaho'),
                  ('IL', 'Illinois'),
                  ('IN', 'Indiana'),
                  ('IA', 'Iowa'),
                  ('KS', 'Kansas'),
                  ('KY', 'Kentucky'),
                  ('LAX', 'Los Angeles'),
                  ('LA', 'Louisiana'),
                  ('ME', 'Maine'),
                  ('MB', 'Manitoba'),
                  ('MAR', 'Maritime'),
                  ('MDC', 'Maryland-DC'),
                  ('MI', 'Michigan'),
                  ('MN', 'Minnesota'),
                  ('MS', 'Mississippi'),
                  ('MO', 'Missouri'),
                  ('MT', 'Montana'),
                  ('NE', 'Nebraska'),
                  ('NV', 'Nevada'),
                  ('NH', 'New Hampshire'),
                  ('NM', 'New Mexico'),
                  ('NLI', 'New York City-Long Island'),
                  ('NL', 'Newfoundland/Labrador'),
                  ('NC', 'North Carolina'),
                  ('ND', 'North Dakota'),
                  ('NTX', 'North Texas'),
                  ('NFL', 'Northern Florida'),
                  ('NNJ', 'Northern New Jersey'),
                  ('NNY', 'Northern New York'),
                  ('NT', 'Northwest Territories/Yukon/Nunavut'),
                  ('OH', 'Ohio'),
                  ('OK', 'Oklahoma'),
                  ('ON', 'Ontario (deprecated)'),
                  ('ONE', 'Ontario East'),
                  ('ONN', 'Ontario North'),
                  ('ONS', 'Ontario South'),
                  ('ORG', 'Orange'),
                  ('OR', 'Oregon'),
                  ('PAC', 'Pacific'),
                  ('PE', 'Prince Edward Island'),
                  ('PR', 'Puerto Rico'),
                  ('QC', 'Quebec'),
                  ('RI', 'Rhode Island'),
                  ('SV', 'Sacramento Valley'),
                  ('SDG', 'San Diego'),
                  ('SF', 'San Francisco'),
                  ('SJV', 'San Joaquin Valley'),
                  ('SB', 'Santa Barbara'),
                  ('SCV', 'Santa Clara Valley'),
                  ('SK', 'Saskatchewan'),
                  ('SC', 'South Carolina'),
                  ('SD', 'South Dakota'),
                  ('STX', 'South Texas'),
                  ('SFL', 'Southern Florida'),
                  ('SNJ', 'Southern New Jersey'),
                  ('TN', 'Tennessee'),
                  ('VI', 'US Virgin Islands'),
                  ('UT', 'Utah'),
                  ('VT', 'Vermont'),
                  ('VA', 'Virginia'),
                  ('WCF', 'West Central Florida'),
                  ('WTX', 'West Texas'),
                  ('WV', 'West Virginia'),
                  ('WMA', 'Western Massachusetts'),
                  ('WNY', 'Western New York'),
                  ('WPA', 'Western Pennsylvania'),
                  ('WWA', 'Western Washington'),
                  ('WI', 'Wisconsin'),
                  ('WY', 'Wyoming'),
                  ],
    'band': ['2190m',
             '630m',
             '560m',
             '160m',
             '80m',
             '60m',
             '40m',
             '30m',
             '20m',
             '17m',
             '15m',
             '12m',
             '10m',
             '8m',
             '6m',
             '5m',
             '4m',
             '2m',
             '1.25m',
             '70cm',
             '33cm',
             '23cm',
             '13cm',
             '9cm',
             '6cm',
             '3cm',
             '1.25cm',
             '6mm',
             '4mm',
             '2.5mm',
             '2mm',
             '1mm',
             'submm', ],
    'qsl_received': ['Y', 'N', 'R', 'I', 'V'],
    'qsl_sent': ['Y', 'N', 'R', 'Q', 'I'],
    'qsl_via': ['B', 'D', 'E', 'M'],
    'qso_complete': ['Y', 'N', 'NIL', '?'],
    'qso_upload_status': ['Y', 'N', 'M'],
    'ant_path': [('G', 'grayline'), ('O', 'other'), ('S', 'short path'), ('L', 'long path')],
    'cont': [('NA', 'North America'),
             ('SA', 'South America'),
             ('EU', 'Europe'),
             ('AF', 'Africa'),
             ('OC', 'Oceana'),
             ('AS', 'Asia'),
             ('AN', 'Antarctica'), ],
    'transmitter': ['0', '1']
}

# if a model field has a value set defined by an enum, this maps the field name to the enum name
qso_field_enum_map = {
    'mode': 'mode',
    'submode': 'sub_mode',
    'ant_path': 'ant_path',
    'arrl_sect': 'arrl_sect',
    'my_arrl_sect': 'arrl_sect',
    'clublog_qso_upload_status': 'qso_upload_status',
    'continent': 'cont',
    'eqsl_qsl_rcvd': 'qsl_received',
    'eqsl_qsl_sent': 'qsl_sent',
    'hamqth_qso_upload_status': 'qso_upload_status',
    'hamlogeu_qso_upload_status': 'qso_upload_status',
    'hrdlog_qso_upload_status': 'qso_upload_status',
    'lotw_qsl_rcvd': 'qsl_received',
    'lotw_qsl_sent': 'qsl_sent',
    'prop_mode': 'prop_mode',
    'qrzcom_qso_upload_status': 'qso_upload_status',
    'qsl_rcvd': 'qsl_received',
    'qsl_rcvd_via': 'qsl_via',
    'qsl_sent': 'qsl_sent',
    'qsl_sent_via': 'qsl_via',
    'qso_complete': 'qso_complete',
    'band': 'band',
    'band_rx': 'band',
    'transmitter_id': 'transmitter',
}

adif_enums['sub_mode'] = []
# models relationships between mode and submode
adif_enums['sub_mode_by_parent_mode'] = {}
for sub, mode in adif_enums['sub_mode_with_parent_mode']:
    adif_enums['sub_mode'].append(sub)
    adif_enums['sub_mode_by_parent_mode'].setdefault(mode, []).append(sub)

cabrillo_modes = ['CW', 'PH', 'FM', 'RY', 'DG']

# convert adif / model main mode value to cabrillo mode value
def adif_mode_to_cabrillo(adif_mode):
    if adif_mode == 'CW':
        return 'CW'
    elif adif_mode == 'FM':
        return 'FM'
    elif adif_mode in ['SSB', 'USB', 'LSB']:
        return 'PH'
    elif adif_mode in ['RTTY', 'RTTYM']:
        return 'RY'
    elif adif_mode in adif_enums['mode']:
        return 'DG'
    return ''

